### ISSUE TITLE
User should not be able to put contradictory options for their filtering options (such as true and false simulatneously for Live)

### ISSUE THREAD

**Issue by yvonneKim** [calebROlson/idb#111]

**Comment by zibbycakes** [comment]
I think this issue will be fixed when the live button is turned into a switch/checkbox. Beyond that, I don't think it's necessary to prevent otherwise contradictory choices. For example, choosing Russia and Austria as regions for Webcam filtering will give you all webcams that are in Russia or in Austria. They contradict, but that is the intention. We have a "no results" page for when the combination of filters doesn't work.

**Comment by zibbycakes** [comment]
I think that we're covering this in another issue. #112
