### ISSUE TITLE
Enhance readability of text on grid page items

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#125]
Perhaps this is just me, but I feel as though it is a little tough to read the text on each grid item on the grid pages, for all 3 models. Maybe the black border could be a little thicker, or some other technique could be employed such as relocating the text, etc?

If not, that's okay but it might enhance usability of the site.

**Comment by zibbycakes** [comment]
This is pretty easy to do. I'm guessing the issue is that google maps for the city grid already has outlined text on it, so sometimes they clash. Here's a side by side comparison on what increasing the outline thickness by .5px does.

1 px thickness (current):
<img width="364" alt="screen shot 2018-04-13 at 4 36 55 pm" src="https://user-images.githubusercontent.com/13042482/38759000-538a9d22-3f39-11e8-9f98-95d3cf001e76.png">
1.5 px thickness:
<img width="368" alt="screen shot 2018-04-13 at 4 38 17 pm" src="https://user-images.githubusercontent.com/13042482/38759018-6be76094-3f39-11e8-8a86-d76d0310b201.png">
css: `text-shadow:rgb(0, 0, 0) -1.5px -1.5px 1px, rgb(0, 0, 0) 1.5px 1.5px 1px, rgb(0, 0, 0) -1.5px 1.5px 1px, rgb(0, 0, 0) 1.5px -1.5px 1px`
